appName: "resume-app"
image: "ghcr.io/tarilen/resume:0.1.0"
imagePullPolicy: "IfNotPresent"
httpGetPath: "/"
httpGetPort: "80"
initialDelaySecondsReadiness: "3"
periodSecondsReadiness: "3"
initialDelaySecondsLiveness: "5"
periodSecondsLiveness: "5"
portName: "http"
port: "80"
targetPort: "80"
containerPort: "80"
replicas: "2"