appName: "resume-app"
ingressName: "nginx"
image: "ghcr.io/tarilen/resume:0.1.0"
imagePullPolicy: "IfNotPresent"
httpGetPath: "/"
httpGetPort: "80"
initialDelaySecondsReadiness: "3"
periodSecondsReadiness: "3"
initialDelaySecondsLiveness: "5"
periodSecondsLiveness: "5"
portName: "http"
httpPort: "80"
httpHost: "resume.local"
targetPort: "80"
containerPort: "80"
minReplicas: "2"
maxReplicas: "5"