name: iac-scan

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'tofu/**'

permissions:
  contents: read
  security-events: write

jobs:
  checkov:
    concurrency:
      group: iac_scan-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Checkov
        id: runCheckov
        uses: bridgecrewio/checkov-action@99bb2caf247dfd9f03cf984373bc6043d4e32ebf # v12.1347.0
        with:
          directory: tofu
          output_format: sarif
          output_file_path: tofu/scan-results.sarif
          soft_fail: true
      - name: DEBUG - where did the sarif land
        if: always()
        run: |
          find . -iname '*.sarif' -print
          ls -la tofu || true

      - name: Upload results to Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38 # v4.37.4
        with:
            sarif_file: tofu/scan-results.sarif
