name: iac-scan

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'tofu/**'

permissions:
  contents: read
  security-events: write

jobs:
  checkov:
    concurrency:
      group: iac_scan-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Checkov
        id: runCheckov
        uses: bridgecrewio/checkov-action@1246d92f57abae29d5db5f9aeeed2a9813e52d7d # v12.3117.0
        with:
          directory: tofu/
          output_format: sarif
          soft_fail: true

      - name: Upload results to Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
            sarif_file: results.sarif
